<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home | Spitchbot</title>
    <meta name="description" content="Twitch Chatbot integrating Spotify API">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/darkly/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Arbutus+Slab">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.css">
</head>
<body>
<nav class="navbar navbar-dark navbar-expand-md" style="z-index: 2;position: absolute;width: 100%;padding: 20px;">
    <div class="container-fluid"><a class="navbar-brand" href="/">Spitchbot</a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span
                class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link active" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="/dashboard">Dashboard</a></li>
                <li class="nav-item"><a class="nav-link" href="/team">Team</a></li>
            </ul>
            <a class="btn ms-auto" role="button" href="/login?force_verify=true">Log In</a></div>
    </div>
</nav>
<footer style="text-align: center;position: absolute;z-index: 2;bottom: 0;left: 50%;transform: translate(-50%);"><span
        style="color: #cccccc;padding: 10;">Made with&nbsp;<i class="fa fa-heart"
                                                              style="color: red;transform: scale(0.70);"></i>&nbsp;by&nbsp;<a
        href="https://twitch.tv/kexesser" style="text-decoration: none;color: inherit;"
        target="_blank">Kexesser</a></span></footer>
<div class="example-box" style="height: 100vh;"><h1><strong>SPITCHBOT</strong></h1>
    <p>Twitch Spotify Connection</p>
    <a class="btn btn-link border-pretty" role="button" href="/dashboard">Dashboard&nbsp;<i
            class="icon ion-android-arrow-forward"></i></a>
    <div style="width: 350px;background-image: linear-gradient(to bottom right, #2d2d2d, #151515);padding: 20px;margin: 20px;border-radius: 20px;box-shadow: 6px 6px 10px 0px #1f1f1f;">
        <div><span>Note that this project is still in development and no functionality can be guaranteed.</span></div>
        <div style="padding-top: 5px;"><span>Check out the project on&nbsp;<a
                href="https://github.com/NotEchoDE/spotifybot" target="_blank"><i
                class="fa fa-github text-info"></i></a>.</span></div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="assets/js/script.min.js"></script>
</body>
</html>